apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: testjava0318aa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testjava0318aa 
  name: testjava0318aa
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: testjava0318aa 
